//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSH.Socrata.WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSH.Socrata.WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socrata is a Seattle-based cloud software company, focused exclusively on democratizing access to government data. We help public sector organizations improve transparency, citizen service and fact-based decision-making by efficiently delivering data to citizens, employees and developers in a user-friendly experience on web, mobile and machine-to-machine interfaces. 
        ///              
        ///   Innovators like the World Bank, Medicare, Data.gov, EnergyStar, New York City, Chicago, San Francisco, Oregon and Maryland [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string AppBarButtonPinText {
            get {
                return ResourceManager.GetString("AppBarButtonPinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string AppBarButtonUnpinText {
            get {
                return ResourceManager.GetString("AppBarButtonUnpinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gov Finder.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a login option....
        /// </summary>
        public static string ChooseLoginOptionText {
            get {
                return ResourceManager.GetString("ChooseLoginOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be empty..
        /// </summary>
        public static string CommentEmptyMessage {
            get {
                return ResourceManager.GetString("CommentEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string InvalidCredentialsMessageTitle {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number..
        /// </summary>
        public static string InValidNumberMessage {
            get {
                return ResourceManager.GetString("InValidNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location service is turned off in phone setting. Do you want to turned it on?.
        /// </summary>
        public static string LocationServiceOffMessage {
            get {
                return ResourceManager.GetString("LocationServiceOffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Service.
        /// </summary>
        public static string LocationServiceText {
            get {
                return ResourceManager.GetString("LocationServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LoginErrorMessageTitle {
            get {
                return ResourceManager.GetString("LoginErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Login.
        /// </summary>
        public static string MicrosoftLoginText {
            get {
                return ResourceManager.GetString("MicrosoftLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection found..
        /// </summary>
        public static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet.
        /// </summary>
        public static string NoInternetMessageTitle {
            get {
                return ResourceManager.GetString("NoInternetMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no phone number.
        /// </summary>
        public static string NoPhoneNumber {
            get {
                return ResourceManager.GetString("NoPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report new feeds..
        /// </summary>
        public static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to socrata.
        /// </summary>
        public static string PeriodicTaskName {
            get {
                return ResourceManager.GetString("PeriodicTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy policy (“Policy”) explains how personal information is collected, used, and disclosed by Socrata, Inc., formerly known as blist, Inc. (“Company”, “we” or “us”) with respect to your use of the web site located at www.Socrata.com (the “Site”) so you can make an informed decision about using the Site and the features and service offered through the Site (the “Services”). We reserve the right to change the provisions of this Policy at any time. We will alert you that changes have been made by indic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary tile deleted..
        /// </summary>
        public static string SecondaryTileDeletedMessage {
            get {
                return ResourceManager.GetString("SecondaryTileDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either input username and password are wrong or there is an error on connecting to Socrata server. Please try again.....
        /// </summary>
        public static string SocrataLoginErrorMessageText {
            get {
                return ResourceManager.GetString("SocrataLoginErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socrata Login.
        /// </summary>
        public static string SocrataLoginText {
            get {
                return ResourceManager.GetString("SocrataLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password cannot be empty.
        /// </summary>
        public static string UsernameAndPassEmptyMessage {
            get {
                return ResourceManager.GetString("UsernameAndPassEmptyMessage", resourceCulture);
            }
        }
    }
}
